option('synctex',
  type: 'feature',
  value: 'auto',
  description: 'SyncTeX integration'
)
option('seccomp',
  type: 'feature',
  value: 'auto',
  description: 'seccomp-based sandbox'
)
option('landlock',
  type: 'feature',
  value: 'auto',
  description: 'landlock-based sandbox'
)
option('manpages',
  type: 'feature',
  value: 'auto',
  description: 'manual pages'
)
option('shell-completions',
  type: 'feature',
  value: 'auto',
  description: 'install bash/fish/zsh completion files'
)
option('tests-x11',
  type: 'feature',
  value: 'auto',
  description: 'run tests with xfvb-run'
)
option('tests-wayland',
  type: 'feature',
  value: 'auto',
  description: 'run tests with weston'
)
option('convert-icon',
  type: 'feature',
  value: 'auto',
  description: 'convert icon to PNG'
)
