.TH ZATHURA 1 zathura\-0.0
.SH NAME
zathura \- a pdf viewer
.SH SYNOPSIS
.B zathura
.RB [\fIFILE\fR] [\fIPASSWORD\fR]
.SH DESCRIPTION
zathura is a pdf viewer based on the poppler pdf rendering library
.SH USAGE
.SS Commands
.TP
.B export
export images, the pdf or attachments to a specified directory
.TP
.B form
show and edit form fields
.TP
.B goto
go to a given page
.TP
.B info
show the document properties
.TP
.B links
show existing links on the page
.TP
.B open
open a pdf document
.TP
.B print
print the document or specific sites of it
.TP
.B quit
close the program
.TP
.B rotate
rotate the page
.TP
.B zoom
set the zoom level
.SS Shortcuts
.TP
.B ^f
next page
.TP
.B ^b
previous page
.TP
.B ^-
zoom in
.TP
.B ^+
zoom out
.TP
.B ^0
original size
.TP
.B ^r
rotate right
.TP
.B ^e
rotate left
.TP
.B ^q
quit program
.TP
.B ^p
print
.TP
.B n
search forwards
.TP
.B N
search backwards
.TP
.B h
scroll left
.TP
.B j
scroll down
.TP
.B k
scroll up
.TP
.B l
scroll right
.TP
.B PgUp
scroll to the top of the page
.TP
.B PgDown
scroll to the bottom of the page
.TP
.B i
best fit
.TP
.B u
adjust width
.TP
.B :
focus inputbar
.TP
.B o
open command
.TP
.B r
rotate command
.TP
.B z
zoom command
.TP
.B g
go to command
.TP
.B /
search
.SH CONFIGURATION
the complete configuration (appearance, shortcuts, commands and other settings) are stored in a seperate file (config.h) where you are able to change and edit everything according to your wishes
