.TH ZATHURA 1 zathura\-VERSION

.SH NAME
zathura \- a document viewer

.SH SYNOPSIS
.B zathura
.RB [options]
.RB [file]
.RB [password]

.SH DESCRIPTION
zathura is a highly customizable and functional document viewer.

.SH OPTIONS
.TP
.B "-e xid"
Reparents to window specified by xid.
.TP
.B "-c path"
Path to the config directory.
.TP
.B "-d path"
Path to the data directory.
.TP
.B "-p path"
Path to the plugin directory.
